### ISSUE TITLE
parallel downloads of repos

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#21]
Currently, given many repos, such as with a bioconductor setup that looks like:

```yaml
Repos:
  - CRAN: "https://cran.microsoft.com/snapshot/2018-11-18"
  - BioCsoft: "https://bioconductor.org/packages/3.8/bioc"
  - BioCann: "https://bioconductor.org/packages/3.8/data/annotation"
  - BioCexp: "https://bioconductor.org/packages/3.8/data/experiment"
  - BioCworkflows: "https://bioconductor.org/packages/3.8/workflows"
```

This can take many seconds as the downloads and parsing proceed sequentially.
