### ISSUE TITLE
Ability to Specify a Repository for One Specific Package

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#299]
I just wanted to install a specific version of a package (as suggested in #85) because the current version on CRAN has an issue that I didn't have with a prior version.  One thought that may be a simpler path to this is to have the option to specify a repository for one package, only.

Something like:

```
Customizations:
  Packags:
    - pillar:
      Repos: https://example.com/older/version
```
