### ISSUE TITLE
`Depends` ignored when installing from tarball or DESCRIPTION

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/pkgr#416]
Take a package `foo` with this `DESCRIPTION`:

```
Package: foo
Version: 1.0.0
Depends:
    R6
Imports:
    withr
```

### `Depends` detected for CRAN-like repo

If I put that in a CRAN-like repo (in this case just a local one), the package in `Depends`, R6, is installed as expected.

```yaml
Version: 1
Packages:
- foo
Repos:
- local: ./repo
- MPN: https://mpn.metworx.com/snapshots/stable/2023-12-05
Cache: pkgcache-repo
Library: lib-repo
```

```
$ ls -1 lib-repo/
R6
foo
withr
```

### `Depends` not detected for `Tarballs`

If I instead use `Tarballs` to point to the source tarball for foo, the `pkgr install` fails with "ERROR: dependency ‘R6’ is not available for package ‘foo’".

```yaml
Version: 1
Tarballs:
- foo_1.0.0.tar.gz
Repos:
- MPN: https://mpn.metworx.com/snapshots/stable/2023-12-05
Cache: pkgcache-tar
Library: lib-tar
```

```
time="2024-02-29T16:42:48-05:00" level=info msg="R Version 4.1.3"
time="2024-02-29T16:42:48-05:00" level=info msg="Package Library will be created" path=lib-tar
time="2024-02-29T16:42:48-05:00" level=info msg="Default package installation type:  source"
time="2024-02-29T16:42:48-05:00" level=info msg="0:1298 (binary:source) packages available in for MPN from https://mpn.metworx.com/snapshots/stable/2023-12-05"
time="2024-02-29T16:42:48-05:00" level=info msg="Package installation cache directory:  pkgcache-tar"
time="2024-02-29T16:42:48-05:00" level=info msg="Database cache directory:  /data/home/kylem/.cache/pkgr/r_packagedb_caches"
time="2024-02-29T16:42:48-05:00" level=info msg="package installation status" installed=0 not_from_pkgr=0 outdated=0 total_packages_required=2
time="2024-02-29T16:42:48-05:00" level=info msg="package installation sources" MPN=1 tarballs=1
time="2024-02-29T16:42:48-05:00" level=info msg="package installation plan" to_install=2 to_update=0
time="2024-02-29T16:42:48-05:00" level=info msg="Library path to install packages: lib-tar\n"
time="2024-02-29T16:42:48-05:00" level=info msg="resolution time 14.72378ms"
time="2024-02-29T16:42:48-05:00" level=info msg="update argument passed. staging packages for update..."
time="2024-02-29T16:42:48-05:00" level=info msg="downloading required packages within directory " dir=/data/home/kylem/scratch/pkgr-dep-testing/pkgcache-tar
time="2024-02-29T16:42:48-05:00" level=info msg="downloading package" package=withr
time="2024-02-29T16:42:48-05:00" level=info msg="all packages downloaded" duration=21.956136ms
time="2024-02-29T16:42:48-05:00" level=info msg="starting initial install"
time="2024-02-29T16:42:51-05:00" level=info msg="Successfully Installed." package=withr remaining=1 repo=MPN version=2.5.0
time="2024-02-29T16:42:51-05:00" level=info msg="starting individual tarball install"
time="2024-02-29T16:42:51-05:00" level=error msg="cmd output" exit_code=1 output="ERROR: dependency ‘R6’ is not available for package ‘foo’\n* removing ‘/data/home/kylem/scratch/pkgr-dep-testing/lib-tar/foo’\n" package=foo stderr="ERROR: dependency ‘R6’ is not available for package ‘foo’\n* removing ‘/data/home/kylem/scratch/pkgr-dep-testing/lib-tar/foo’\n" stdout=
time="2024-02-29T16:42:51-05:00" level=error msg="error installing package" error="exit status 1" install_type=tarball installed_from=pkgcache-tar/a8516ee48f236c72/foo pkg=foo remaining=0 source=foo_1.0.0.tar.gz
time="2024-02-29T16:42:51-05:00" level=info msg="total package install time" duration=2.627162426s
time="2024-02-29T16:42:51-05:00" level=info msg="duration:2.627945394s"
```

### `Depends` not detected for `Descriptions`

And if I point to foo's `DESCRIPTION`, R6 is **not** installed.

```yaml
Version: 1
Descriptions:
- foo/DESCRIPTION
Repos:
- MPN: https://mpn.metworx.com/snapshots/stable/2023-12-05
Cache: pkgcache-desc
Library: lib-desc
```

```
$ ls -1 lib-desc/
withr
```

---

The above is with the pkgr v3.1.1.

The attached tarball has the setup code for these cases (invoke `make` to run them all).

[pkgr-depends-test.tar.gz](https://github.com/metrumresearchgroup/pkgr/files/14453993/pkgr-depends-test.tar.gz)
